<a href="https://colab.research.google.com/github/Satya-Siba-Nayak/IRIS-EDA/blob/main/Practical_1_Satya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practical 1

**Name : Satya Nayak**

**PRN : 1272240768**

Q.1 Write a program to load the Iris dataset and display the first 5 rows using Pandas.

In [ ]:
import pandas as pd
df=pd.read_csv('/content/Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Q.2 Write a Pandas command to get a random sample of 5 rows from the Iris dataset?

In [ ]:
df.sample(5)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
90,91,5.5,2.6,4.4,1.2,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
1,2,4.9,3.0,1.4,0.2,Iris-setosa
20,21,5.4,3.4,1.7,0.2,Iris-setosa

Q.3 Write a Pandas command to display the number of rows and columns in the Iris dataset.

In [ ]:
df.shape

(150, 6)

Q.4 Write a program to print all column names in the Iris dataset.

In [ ]:
print(df.columns)

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

Q.5 Write a script to print the data types of all columns in the Iris dataset?

In [ ]:
print(df.dtypes)

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

Q.6 Write a Pandas command to check how many missing values exist in each column of the Iris dataset?

In [ ]:
print(df.isnull().sum())

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

Q.7 Display the unique species present in the "Species" column?

In [ ]:
print(df["Species"].unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

Q.8 Count how many times each species appears in the dataset.

In [ ]:
print(df["Species"].value_counts())

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

Q.9 Compute the mean, median, and standard deviation for the "SepalWidthCm" column in the Iris dataset?

In [ ]:
print("Mean:", df["SepalWidthCm"].mean())
print("Median:", df["SepalWidthCm"].median())
print("Standard Deviation:", df["SepalWidthCm"].std())

Mean: 3.0540000000000003
Median: 3.0
Standard Deviation: 0.4335943113621737

Q.10 Remove the "Id" column from the Iris dataset and display the first 5 rows of the modified DataFrame.

In [ ]:
df_modified = df.drop("Id", axis=1)
df_modified.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa